#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Initialize Doris ODS tables for outdoor-data-validator (Phase 2).

ODS 层设计原则（ARCH14）：
- 包含 API 接口返回的所有字段，不做业务筛选
- 英文字段直接使用原名；中文字段转为英文 snake_case，COMMENT 写原中文
- 嵌套 list/dict 序列化为 JSON TEXT
- 每表统一追加 etl_time DATETIME COMMENT 'ETL写入时间'

全量拉取起始时间（ARCH16）：EARLIEST_DATE = "2026-03-01"
测试完成后统一修改此常量以拉取更早历史数据。
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'bi', 'python_sdk', 'outdoor_collector'))

import pymysql
from doris_config import DorisConfig

# ---------------------------------------------------------------------------
# TripleWhale ODS 表
# ---------------------------------------------------------------------------

_TW_PIXEL_ORDERS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_pixel_orders (
    order_id                        VARCHAR(64)  NOT NULL,
    event_date                      DATE         NULL,
    created_at                      DATETIME     NULL,
    order_name                      VARCHAR(64)  NULL,
    shop_id                         VARCHAR(128) NULL,
    shop_name                       VARCHAR(64)  NULL,
    shop_timezone                   VARCHAR(64)  NULL,
    integration_id                  VARCHAR(128) NULL,
    platform                        VARCHAR(32)  NULL,
    channel                         VARCHAR(128) NULL,
    source_name                     VARCHAR(64)  NULL,
    financial_status                VARCHAR(32)  NULL,
    fulfillment_status              VARCHAR(32)  NULL,
    cancelled_at                    DATETIME     NULL,
    currency                        VARCHAR(8)   NULL,
    currency_rate                   DOUBLE       NULL,
    gross_sales                     DOUBLE       NULL,
    gross_product_sales             DOUBLE       NULL,
    order_revenue                   DOUBLE       NULL,
    refund_money                    DOUBLE       NULL,
    discount_amount                 DOUBLE       NULL,
    discount_code                   VARCHAR(64)  NULL,
    shipping_costs                  DOUBLE       NULL,
    shipping_price                  DOUBLE       NULL,
    shipping_tax                    DOUBLE       NULL,
    handling_fees                   DOUBLE       NULL,
    payment_gateway_costs           DOUBLE       NULL,
    taxes                           DOUBLE       NULL,
    cogs                            DOUBLE       NULL,
    cost_of_goods                   DOUBLE       NULL,
    orders_quantity                 DOUBLE       NULL,
    product_quantity_sold_in_order  DOUBLE       NULL,
    custom_gross_profit             DOUBLE       NULL,
    custom_gross_sales              DOUBLE       NULL,
    custom_net_revenue              DOUBLE       NULL,
    custom_combined_gross_profit    DOUBLE       NULL,
    custom_combined_gross_sales     DOUBLE       NULL,
    custom_combined_net_revenue     DOUBLE       NULL,
    custom_expenses                 DOUBLE       NULL,
    custom_number                   DOUBLE       NULL,
    custom_orders_quantity          DOUBLE       NULL,
    custom_total_items_quantity     DOUBLE       NULL,
    custom_status                   VARCHAR(64)  NULL,
    custom_string                   VARCHAR(255) NULL,
    customer_id                     VARCHAR(64)  NULL,
    customer_first_name             VARCHAR(128) NULL,
    customer_last_name              VARCHAR(128) NULL,
    customer_email                  VARCHAR(255) NULL,
    is_new_customer                 TINYINT      NULL,
    is_subscription_order           TINYINT      NULL,
    is_first_order_in_subscription  TINYINT      NULL,
    triple_id                       VARCHAR(64)  NULL,
    session_id                      VARCHAR(128) NULL,
    model                           VARCHAR(64)  NULL,
    attribution_window              VARCHAR(32)  NULL,
    linear_weight                   DOUBLE       NULL,
    ad_id                           VARCHAR(128) NULL,
    adset_id                        VARCHAR(128) NULL,
    campaign_id                     VARCHAR(128) NULL,
    ad_name                         VARCHAR(255) NULL,
    adset_name                      VARCHAR(255) NULL,
    campaign_name                   VARCHAR(255) NULL,
    campaign_type                   VARCHAR(64)  NULL,
    account_id                      VARCHAR(64)  NULL,
    click_date                      DATE         NULL,
    click_ts                        DATETIME     NULL,
    billing_city                    VARCHAR(128) NULL,
    billing_country                 VARCHAR(128) NULL,
    billing_country_code            VARCHAR(8)   NULL,
    billing_province                VARCHAR(128) NULL,
    shipping_city                   VARCHAR(128) NULL,
    shipping_country                VARCHAR(128) NULL,
    shipping_country_code           VARCHAR(8)   NULL,
    shipping_country_name           VARCHAR(128) NULL,
    shipping_state                  VARCHAR(128) NULL,
    shipping_state_code             VARCHAR(8)   NULL,
    shipping_zip                    VARCHAR(32)  NULL,
    customer_from_city              VARCHAR(128) NULL,
    customer_from_country_code      VARCHAR(8)   NULL,
    customer_from_country_name      VARCHAR(128) NULL,
    customer_from_state_code        VARCHAR(8)   NULL,
    session_city                    VARCHAR(128) NULL,
    session_country                 VARCHAR(128) NULL,
    browser                         VARCHAR(64)  NULL,
    device                          VARCHAR(64)  NULL,
    landing_page                    TEXT         NULL,
    event_hour                      DOUBLE       NULL,
    utm_source                      VARCHAR(128) NULL,
    utm_medium                      VARCHAR(128) NULL,
    customer_tags                   TEXT         NULL,
    discount_codes                  TEXT         NULL,
    products_info                   TEXT         NULL,
    tags                            TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(order_id)
DISTRIBUTED BY HASH(order_id) BUCKETS 8
PROPERTIES ("replication_num" = "1")"""

_TW_PIXEL_JOINED = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_pixel_joined (
    event_date                          DATE         NOT NULL,
    channel                             VARCHAR(128) NOT NULL,
    account_id                          VARCHAR(64)  NOT NULL,
    campaign_id                         VARCHAR(128) NOT NULL,
    adset_id                            VARCHAR(128) NOT NULL,
    ad_id                               VARCHAR(128) NOT NULL,
    ad_name                             VARCHAR(255) NULL,
    ad_copy                             VARCHAR(255) NULL,
    ad_type                             VARCHAR(32)  NULL,
    ad_status                           VARCHAR(32)  NULL,
    ad_image_url                        TEXT         NULL,
    ad_bid_amount                       DOUBLE       NULL,
    adset_name                          VARCHAR(255) NULL,
    adset_status                        VARCHAR(32)  NULL,
    adset_bid_amount                    DOUBLE       NULL,
    adset_bid_strategy                  VARCHAR(64)  NULL,
    adset_daily_budget                  DOUBLE       NULL,
    adset_lifetime_budget               DOUBLE       NULL,
    campaign_name                       VARCHAR(255) NULL,
    campaign_status                     VARCHAR(32)  NULL,
    campaign_type                       VARCHAR(64)  NULL,
    campaign_sub_type                   VARCHAR(64)  NULL,
    campaign_bid_strategy               VARCHAR(64)  NULL,
    campaign_daily_budget               DOUBLE       NULL,
    campaign_lifetime_budget            DOUBLE       NULL,
    model                               VARCHAR(64)  NULL,
    attribution_window                  VARCHAR(32)  NULL,
    integration_id                      VARCHAR(128) NULL,
    original_provider_id                VARCHAR(64)  NULL,
    provider_id                         VARCHAR(64)  NULL,
    shop_id                             VARCHAR(128) NULL,
    shop_name                           VARCHAR(64)  NULL,
    impressions                         DOUBLE       NULL,
    clicks                              DOUBLE       NULL,
    outbound_clicks                     DOUBLE       NULL,
    spend                               DOUBLE       NULL,
    non_tracked_spend                   DOUBLE       NULL,
    orders_quantity                     DOUBLE       NULL,
    click_orders                        DOUBLE       NULL,
    view_orders                         DOUBLE       NULL,
    order_revenue                       DOUBLE       NULL,
    click_revenue                       DOUBLE       NULL,
    view_revenue                        DOUBLE       NULL,
    gross_sales                         DOUBLE       NULL,
    gross_product_sales                 DOUBLE       NULL,
    product_quantity_sold_in_order      DOUBLE       NULL,
    refund_money                        DOUBLE       NULL,
    new_customer_orders                 DOUBLE       NULL,
    new_customer_order_revenue          DOUBLE       NULL,
    new_customer_gross_sales            DOUBLE       NULL,
    new_customer_cogs                   DOUBLE       NULL,
    custom_gross_profit                 DOUBLE       NULL,
    custom_gross_sales                  DOUBLE       NULL,
    custom_net_revenue                  DOUBLE       NULL,
    custom_combined_gross_profit        DOUBLE       NULL,
    custom_combined_gross_sales         DOUBLE       NULL,
    custom_combined_net_revenue         DOUBLE       NULL,
    custom_expenses                     DOUBLE       NULL,
    custom_orders_quantity              DOUBLE       NULL,
    custom_total_items_quantity         DOUBLE       NULL,
    cogs                                DOUBLE       NULL,
    cost_of_goods                       DOUBLE       NULL,
    total_video_view                    DOUBLE       NULL,
    video_p25_watched                   DOUBLE       NULL,
    video_p50_watched                   DOUBLE       NULL,
    video_p75_watched                   DOUBLE       NULL,
    video_p100_watched                  DOUBLE       NULL,
    meta_conversion_value               DOUBLE       NULL,
    meta_facebook_orders                DOUBLE       NULL,
    non_meta_facebook_orders            DOUBLE       NULL,
    one_day_view_conversion_value       DOUBLE       NULL,
    one_day_view_purchases              DOUBLE       NULL,
    seven_day_view_conversion_value     DOUBLE       NULL,
    seven_day_view_purchases            DOUBLE       NULL,
    website_purchases                   DOUBLE       NULL,
    channel_reported_all_conversions    DOUBLE       NULL,
    channel_reported_conversion_value   DOUBLE       NULL,
    channel_reported_conversions        DOUBLE       NULL,
    channel_reported_onsite_conversion_value DOUBLE  NULL,
    channel_reported_onsite_purchases   DOUBLE       NULL,
    channel_reported_visits             DOUBLE       NULL,
    subscription_quantity               DOUBLE       NULL,
    subscriptions_arr                   DOUBLE       NULL,
    i_revenue                           DOUBLE       NULL,
    i_roas                              DOUBLE       NULL,
    experiment_CPIC                     VARCHAR(255) NULL,
    experiment_CPIC_lower               VARCHAR(255) NULL,
    experiment_CPIC_upper               VARCHAR(255) NULL,
    experiment_conversions_incremental  VARCHAR(255) NULL,
    experiment_conversions_incremental_lower VARCHAR(255) NULL,
    experiment_conversions_incremental_share_percent VARCHAR(255) NULL,
    experiment_conversions_incremental_upper VARCHAR(255) NULL,
    experiment_event_date               VARCHAR(255) NULL,
    experiment_i_ROAS                   VARCHAR(255) NULL,
    experiment_i_ROAS_lower_bound       VARCHAR(255) NULL,
    experiment_i_ROAS_upper_bound       VARCHAR(255) NULL,
    experiment_incremental_conversions_confidence_percent VARCHAR(255) NULL,
    experiment_incremental_revenue_confidence_percent VARCHAR(255) NULL,
    experiment_revenue_incremental_share_percent VARCHAR(255) NULL,
    incremental_revenue_experiment      VARCHAR(255) NULL,
    incremental_revenue_lower_bound_experiment VARCHAR(255) NULL,
    incremental_revenue_upper_bound_experiment VARCHAR(255) NULL,
    channel_type                        VARCHAR(64)  NULL,
    creative_id                         VARCHAR(64)  NULL,
    creative_cta_type                   VARCHAR(64)  NULL,
    creative_format                     VARCHAR(64)  NULL,
    creative_distribution_format        VARCHAR(64)  NULL,
    is_utm_valid                        TINYINT      NULL,
    suggested_budget                    DOUBLE       NULL,
    url_template                        TEXT         NULL,
    video_url                           TEXT         NULL,
    video_url_iframe                    TEXT         NULL,
    video_url_source                    TEXT         NULL,
    video_duration                      DOUBLE       NULL,
    number_of_image_assets              DOUBLE       NULL,
    number_of_video_assets              DOUBLE       NULL,
    ad_copies                           TEXT         NULL,
    ad_titles                           TEXT         NULL,
    ad_ai_recommendation                TEXT         NULL,
    ad_ai_roas_pacing                   TEXT         NULL,
    adset_ai_recommendation             TEXT         NULL,
    adset_ai_roas_pacing                TEXT         NULL,
    campaign_ai_recommendation          TEXT         NULL,
    campaign_ai_roas_pacing             TEXT         NULL,
    channel_ai_recommendation           TEXT         NULL,
    channel_ai_roas_pacing              TEXT         NULL,
    discount_codes                      TEXT         NULL,
    links                               TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date, channel, account_id, campaign_id, adset_id, ad_id)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_SESSIONS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_sessions (
    session_id              VARCHAR(128) NOT NULL,
    event_date              DATE         NOT NULL,
    event_date_timezone     VARCHAR(64)  NULL,
    event_hour              INT          NULL,
    session_start_ts        DATETIME     NULL,
    session_elapsed_time    DOUBLE       NULL,
    session_page_views      INT          NULL,
    shop_id                 VARCHAR(128) NULL,
    shop_name               VARCHAR(64)  NULL,
    domain                  VARCHAR(128) NULL,
    triple_id               VARCHAR(64)  NULL,
    channel                 VARCHAR(128) NULL,
    source                  VARCHAR(128) NULL,
    utm_source              VARCHAR(128) NULL,
    utm_medium              VARCHAR(128) NULL,
    ad_id                   VARCHAR(128) NULL,
    adset_id                VARCHAR(128) NULL,
    campaign_id             VARCHAR(128) NULL,
    keyword_id              VARCHAR(128) NULL,
    landing_page            TEXT         NULL,
    browser                 VARCHAR(64)  NULL,
    device                  VARCHAR(64)  NULL,
    device_model            VARCHAR(64)  NULL,
    country                 VARCHAR(64)  NULL,
    country_code            VARCHAR(8)   NULL,
    city                    VARCHAR(128) NULL,
    is_new_visitor          TINYINT      NULL,
    ms_country              VARCHAR(8)   NULL,
    ms_country_name         VARCHAR(64)  NULL
) ENGINE=OLAP UNIQUE KEY(session_id)
DISTRIBUTED BY HASH(session_id) BUCKETS 8
PROPERTIES ("replication_num" = "1")"""

_TW_PRODUCT_ANALYTICS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_product_analytics (
    event_date                      DATE         NOT NULL,
    entity                          VARCHAR(32)  NOT NULL,
    id                              VARCHAR(64)  NOT NULL,
    product_id                      VARCHAR(64)  NULL,
    product_name                    TEXT         NULL,
    product_title                   TEXT         NULL,
    name                            TEXT         NULL,
    title                           TEXT         NULL,
    product_status                  VARCHAR(32)  NULL,
    product_image_url               TEXT         NULL,
    sku                             VARCHAR(128) NULL,
    vendor                          VARCHAR(128) NULL,
    number_of_ads                   DOUBLE       NULL,
    inventory_quantity              DOUBLE       NULL,
    collection_id                   VARCHAR(64)  NULL,
    collection_name                 VARCHAR(255) NULL,
    variant_id                      VARCHAR(64)  NULL,
    variant_name                    VARCHAR(255) NULL,
    variant_title                   VARCHAR(255) NULL,
    shop_id                         VARCHAR(128) NULL,
    shop_name                       VARCHAR(64)  NULL,
    clicks                          DOUBLE       NULL,
    impressions                     DOUBLE       NULL,
    visits                          DOUBLE       NULL,
    customers                       DOUBLE       NULL,
    orders                          DOUBLE       NULL,
    revenue                         DOUBLE       NULL,
    total_order_value               DOUBLE       NULL,
    total_items_sold                DOUBLE       NULL,
    spend                           DOUBLE       NULL,
    fulfillment_costs               DOUBLE       NULL,
    new_customer_orders             DOUBLE       NULL,
    new_customer_revenue            DOUBLE       NULL,
    new_customer_total_order_value  DOUBLE       NULL,
    new_customer_total_items_sold   DOUBLE       NULL,
    new_customer_fulfillment_costs  DOUBLE       NULL,
    repeat_customer                 DOUBLE       NULL,
    returns                         DOUBLE       NULL,
    added_to_cart_events            DOUBLE       NULL,
    added_to_cart_items             DOUBLE       NULL,
    product_tags                    TEXT         NULL,
    images                          TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date, entity, id)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_PIXEL_KEYWORDS_JOINED = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_pixel_keywords_joined (
    event_date                          DATE         NOT NULL,
    channel                             VARCHAR(128) NOT NULL,
    keyword_id                          VARCHAR(128) NOT NULL,
    keyword_text                        VARCHAR(255) NULL,
    keyword_match_type                  VARCHAR(32)  NULL,
    keyword_status                      VARCHAR(32)  NULL,
    keyword_system_serving_status       VARCHAR(64)  NULL,
    keyword_effective_cpc_bid           DOUBLE       NULL,
    keyword_cpc_bid                     DOUBLE       NULL,
    keyword_quality_score               DOUBLE       NULL,
    account_id                          VARCHAR(64)  NULL,
    campaign_id                         VARCHAR(128) NULL,
    campaign_name                       VARCHAR(255) NULL,
    campaign_status                     VARCHAR(32)  NULL,
    campaign_bid_strategy               VARCHAR(64)  NULL,
    adset_id                            VARCHAR(128) NULL,
    adset_name                          VARCHAR(255) NULL,
    adset_status                        VARCHAR(32)  NULL,
    adset_bid_amount                    DOUBLE       NULL,
    adset_bid_strategy                  VARCHAR(64)  NULL,
    integration_id                      VARCHAR(128) NULL,
    original_provider_id                VARCHAR(64)  NULL,
    provider_id                         VARCHAR(64)  NULL,
    model                               VARCHAR(64)  NULL,
    attribution_window                  VARCHAR(32)  NULL,
    impressions                         DOUBLE       NULL,
    clicks                              DOUBLE       NULL,
    spend                               DOUBLE       NULL,
    orders_quantity                     DOUBLE       NULL,
    click_orders                        DOUBLE       NULL,
    view_orders                         DOUBLE       NULL,
    order_revenue                       DOUBLE       NULL,
    click_revenue                       DOUBLE       NULL,
    view_revenue                        DOUBLE       NULL,
    gross_sales                         DOUBLE       NULL,
    gross_product_sales                 DOUBLE       NULL,
    product_quantity_sold_in_order      DOUBLE       NULL,
    refund_money                        DOUBLE       NULL,
    new_customer_orders                 DOUBLE       NULL,
    new_customer_order_revenue          DOUBLE       NULL,
    new_customer_gross_sales            DOUBLE       NULL,
    new_customer_cogs                   DOUBLE       NULL,
    custom_gross_profit                 DOUBLE       NULL,
    custom_gross_sales                  DOUBLE       NULL,
    custom_net_revenue                  DOUBLE       NULL,
    custom_combined_gross_profit        DOUBLE       NULL,
    custom_combined_gross_sales         DOUBLE       NULL,
    custom_combined_net_revenue         DOUBLE       NULL,
    custom_expenses                     DOUBLE       NULL,
    custom_orders_quantity              DOUBLE       NULL,
    custom_total_items_quantity         DOUBLE       NULL,
    cogs                                DOUBLE       NULL,
    cost_of_goods                       DOUBLE       NULL,
    one_day_view_conversion_value       DOUBLE       NULL,
    one_day_view_purchases              DOUBLE       NULL,
    seven_day_view_conversion_value     DOUBLE       NULL,
    seven_day_view_purchases            DOUBLE       NULL,
    website_purchases                   DOUBLE       NULL,
    channel_reported_all_conversions    DOUBLE       NULL,
    channel_reported_conversion_value   DOUBLE       NULL,
    subscription_quantity               DOUBLE       NULL,
    subscriptions_arr                   DOUBLE       NULL,
    experiment_CPIC                     VARCHAR(255) NULL,
    experiment_event_date               VARCHAR(255) NULL,
    experiment_i_ROAS                   VARCHAR(255) NULL,
    experiment_i_ROAS_lower_bound       VARCHAR(255) NULL,
    experiment_i_ROAS_upper_bound       VARCHAR(255) NULL,
    shop_id                             VARCHAR(128) NULL,
    shop_name                           VARCHAR(64)  NULL,
    discount_codes                      TEXT         NULL,
    links                               TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date, channel, keyword_id)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_ADS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_ads (
    event_date                          DATE         NOT NULL,
    channel                             VARCHAR(128) NOT NULL,
    account_id                          VARCHAR(64)  NOT NULL,
    campaign_id                         VARCHAR(128) NOT NULL,
    adset_id                            VARCHAR(128) NOT NULL,
    ad_id                               VARCHAR(128) NOT NULL,
    ad_name                             VARCHAR(255) NULL,
    ad_status                           VARCHAR(32)  NULL,
    ad_type                             VARCHAR(32)  NULL,
    ad_image_url                        TEXT         NULL,
    ad_title                            VARCHAR(255) NULL,
    ad_copy                             VARCHAR(255) NULL,
    ad_post_id                          VARCHAR(64)  NULL,
    ad_bid_amount                       DOUBLE       NULL,
    adset_name                          VARCHAR(255) NULL,
    adset_status                        VARCHAR(32)  NULL,
    adset_bid_amount                    DOUBLE       NULL,
    adset_bid_strategy                  VARCHAR(64)  NULL,
    adset_daily_budget                  DOUBLE       NULL,
    adset_lifetime_budget               DOUBLE       NULL,
    adset_target_cpa                    DOUBLE       NULL,
    adset_target_roas                   DOUBLE       NULL,
    adset_targeting                     TEXT         NULL,
    campaign_name                       VARCHAR(255) NULL,
    campaign_status                     VARCHAR(32)  NULL,
    campaign_type                       VARCHAR(64)  NULL,
    campaign_sub_type                   VARCHAR(64)  NULL,
    campaign_bid_strategy               VARCHAR(64)  NULL,
    campaign_daily_budget               DOUBLE       NULL,
    campaign_lifetime_budget            DOUBLE       NULL,
    campaign_target_cpa                 DOUBLE       NULL,
    campaign_target_roas                DOUBLE       NULL,
    campaign_created_at                 VARCHAR(255) NULL,
    model                               VARCHAR(64)  NULL,
    attribution_window                  VARCHAR(32)  NULL,
    integration_id                      VARCHAR(128) NULL,
    is_utm_valid                        TINYINT      NULL,
    currency                            VARCHAR(8)   NULL,
    currency_rate                       DOUBLE       NULL,
    event_hour                          INT          NULL,
    destination_url                     TEXT         NULL,
    url_template                        TEXT         NULL,
    video_url                           TEXT         NULL,
    video_url_iframe                    TEXT         NULL,
    video_url_source                    TEXT         NULL,
    video_duration                      DOUBLE       NULL,
    asset_id                            VARCHAR(128) NULL,
    asset_type                          VARCHAR(64)  NULL,
    creative_id                         VARCHAR(128) NULL,
    creative_cta_type                   VARCHAR(64)  NULL,
    creative_format                     VARCHAR(64)  NULL,
    creative_distribution_format        VARCHAR(64)  NULL,
    impressions                         DOUBLE       NULL,
    clicks                              DOUBLE       NULL,
    outbound_clicks                     DOUBLE       NULL,
    spend                               DOUBLE       NULL,
    non_tracked_spend                   DOUBLE       NULL,
    engagements                         DOUBLE       NULL,
    follows                             DOUBLE       NULL,
    weight                              DOUBLE       NULL,
    three_second_video_view             DOUBLE       NULL,
    video_p25_watched                   DOUBLE       NULL,
    video_p50_watched                   DOUBLE       NULL,
    video_p75_watched                   DOUBLE       NULL,
    video_p95_watched                   DOUBLE       NULL,
    video_p100_watched                  DOUBLE       NULL,
    conversions                         DOUBLE       NULL,
    all_conversions                     DOUBLE       NULL,
    conversion_value                    DOUBLE       NULL,
    all_conversion_value                DOUBLE       NULL,
    one_day_click_conversion_value      DOUBLE       NULL,
    one_day_click_purchases             DOUBLE       NULL,
    one_day_click_comments              DOUBLE       NULL,
    one_day_click_likes                 DOUBLE       NULL,
    one_day_click_link_clicks           DOUBLE       NULL,
    one_day_click_reactions             DOUBLE       NULL,
    one_day_click_shares                DOUBLE       NULL,
    seven_day_click_conversion_value    DOUBLE       NULL,
    seven_day_click_purchases           DOUBLE       NULL,
    seven_day_click_comments            DOUBLE       NULL,
    seven_day_click_likes               DOUBLE       NULL,
    seven_day_click_link_clicks         DOUBLE       NULL,
    seven_day_click_reactions           DOUBLE       NULL,
    seven_day_click_shares              DOUBLE       NULL,
    twenty_eight_day_click_conversion_value DOUBLE   NULL,
    twenty_eight_day_click_purchases    DOUBLE       NULL,
    twenty_eight_day_click_link_clicks  DOUBLE       NULL,
    twenty_eight_day_view_conversion_value DOUBLE    NULL,
    twenty_eight_day_view_purchases     DOUBLE       NULL,
    one_day_view_conversion_value       DOUBLE       NULL,
    one_day_view_purchases              DOUBLE       NULL,
    seven_day_view_conversion_value     DOUBLE       NULL,
    seven_day_view_purchases            DOUBLE       NULL,
    meta_conversion_value               DOUBLE       NULL,
    meta_purchases                      DOUBLE       NULL,
    website_purchases                   DOUBLE       NULL,
    onsite_purchases                    DOUBLE       NULL,
    onsite_conversion_value             DOUBLE       NULL,
    onsite_one_day_click_conversion_value DOUBLE     NULL,
    onsite_one_day_click_purchases      DOUBLE       NULL,
    onsite_one_day_view_conversion_value DOUBLE      NULL,
    onsite_one_day_view_purchases       DOUBLE       NULL,
    onsite_seven_day_click_conversion_value DOUBLE   NULL,
    onsite_seven_day_click_purchases    DOUBLE       NULL,
    onsite_seven_day_view_conversion_value DOUBLE    NULL,
    onsite_seven_day_view_purchases     DOUBLE       NULL,
    onsite_twenty_eight_day_click_conversion_value DOUBLE NULL,
    onsite_twenty_eight_day_click_purchases DOUBLE   NULL,
    onsite_twenty_eight_day_view_conversion_value DOUBLE NULL,
    onsite_twenty_eight_day_view_purchases DOUBLE    NULL,
    search_impression_share             DOUBLE       NULL,
    search_impressions                  DOUBLE       NULL,
    search_absolute_top_impression_share DOUBLE      NULL,
    search_absolute_top_impressions     DOUBLE       NULL,
    search_top_impression_share         DOUBLE       NULL,
    search_top_impressions              DOUBLE       NULL,
    search_budget_lost_absolute_top_impression_share DOUBLE NULL,
    search_budget_lost_absolute_top_impressions DOUBLE NULL,
    search_budget_lost_top_impression_share DOUBLE   NULL,
    search_budget_lost_top_impressions  DOUBLE       NULL,
    search_rank_lost_impression_share   DOUBLE       NULL,
    search_rank_lost_impressions        DOUBLE       NULL,
    search_rank_lost_top_impression_share DOUBLE     NULL,
    search_rank_lost_top_impressions    DOUBLE       NULL,
    total_complete_payment_rate         DOUBLE       NULL,
    total_on_web_order_value            DOUBLE       NULL,
    visits                              DOUBLE       NULL,
    shop_id                             VARCHAR(128) NULL,
    shop_name                           VARCHAR(64)  NULL,
    actions                             TEXT         NULL,
    ad_copies                           TEXT         NULL,
    ad_titles                           TEXT         NULL,
    ad_ai_recommendation                TEXT         NULL,
    ad_ai_roas_pacing                   TEXT         NULL,
    adset_ai_recommendation             TEXT         NULL,
    adset_ai_roas_pacing                TEXT         NULL,
    campaign_ai_recommendation          TEXT         NULL,
    campaign_ai_roas_pacing             TEXT         NULL,
    channel_ai_recommendation           TEXT         NULL,
    channel_ai_roas_pacing              TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date, channel, account_id, campaign_id, adset_id, ad_id)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_SOCIAL_MEDIA_COMMENTS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_social_media_comments (
    comment_id              VARCHAR(128) NOT NULL,
    post_id                 VARCHAR(128) NULL,
    page_id                 VARCHAR(128) NULL,
    user_id                 VARCHAR(128) NULL,
    account_id              VARCHAR(128) NULL,
    integration_id          VARCHAR(128) NULL,
    channel                 VARCHAR(64)  NULL,
    comment_text            TEXT         NULL,
    created_at              DATETIME     NULL,
    visibility_status       VARCHAR(64)  NULL,
    visibility_changed_at   DATETIME     NULL,
    visibility_changed_by   VARCHAR(128) NULL,
    risk                    VARCHAR(32)  NULL,
    sentiment               VARCHAR(32)  NULL,
    topic                   VARCHAR(64)  NULL
) ENGINE=OLAP UNIQUE KEY(comment_id)
DISTRIBUTED BY HASH(comment_id) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_SOCIAL_MEDIA_PAGES = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_social_media_pages (
    event_date              DATE         NOT NULL,
    page_id                 VARCHAR(128) NOT NULL,
    channel                 VARCHAR(64)  NOT NULL,
    page_name               VARCHAR(128) NULL,
    page_permalink          TEXT         NULL,
    website                 TEXT         NULL,
    about                   TEXT         NULL,
    category                VARCHAR(128) NULL,
    cover_url               TEXT         NULL,
    image_url               TEXT         NULL,
    fan_adds                DOUBLE       NULL,
    fan_removes             DOUBLE       NULL,
    impressions             DOUBLE       NULL,
    impressions_paid        DOUBLE       NULL,
    impressions_unique      DOUBLE       NULL,
    impressions_viral       DOUBLE       NULL,
    video_views             DOUBLE       NULL,
    views_total             DOUBLE       NULL
) ENGINE=OLAP UNIQUE KEY(event_date, page_id, channel)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_CREATIVES = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_creatives (
    event_date                          DATE         NOT NULL,
    channel                             VARCHAR(128) NOT NULL,
    ad_id                               VARCHAR(128) NOT NULL,
    asset_id                            VARCHAR(128) NOT NULL,
    creative_id                         VARCHAR(128) NULL,
    asset_type                          VARCHAR(64)  NULL,
    ad_type                             VARCHAR(64)  NULL,
    ad_title                            VARCHAR(255) NULL,
    ad_copy                             VARCHAR(255) NULL,
    ad_image_url                        TEXT         NULL,
    video_url                           TEXT         NULL,
    video_url_iframe                    TEXT         NULL,
    video_url_source                    TEXT         NULL,
    video_duration                      DOUBLE       NULL,
    destination_url                     TEXT         NULL,
    url_template                        TEXT         NULL,
    creative_cta_type                   VARCHAR(64)  NULL,
    creative_format                     VARCHAR(64)  NULL,
    creative_distribution_format        VARCHAR(64)  NULL,
    account_id                          VARCHAR(64)  NULL,
    campaign_id                         VARCHAR(128) NULL,
    campaign_name                       VARCHAR(255) NULL,
    adset_id                            VARCHAR(128) NULL,
    adset_name                          VARCHAR(255) NULL,
    model                               VARCHAR(64)  NULL,
    attribution_window                  VARCHAR(32)  NULL,
    number_of_ads                       DOUBLE       NULL,
    shop_id                             VARCHAR(128) NULL,
    shop_name                           VARCHAR(64)  NULL,
    impressions                         DOUBLE       NULL,
    clicks                              DOUBLE       NULL,
    outbound_clicks                     DOUBLE       NULL,
    spend                               DOUBLE       NULL,
    non_tracked_spend                   DOUBLE       NULL,
    three_second_video_view             DOUBLE       NULL,
    thruplays                           DOUBLE       NULL,
    total_video_view                    DOUBLE       NULL,
    video_p25_watched                   DOUBLE       NULL,
    video_p50_watched                   DOUBLE       NULL,
    video_p75_watched                   DOUBLE       NULL,
    video_p95_watched                   DOUBLE       NULL,
    video_p100_watched                  DOUBLE       NULL,
    orders_quantity                     DOUBLE       NULL,
    order_revenue                       DOUBLE       NULL,
    gross_product_sales                 DOUBLE       NULL,
    new_customer_orders                 DOUBLE       NULL,
    new_customer_order_revenue          DOUBLE       NULL,
    new_customer_cogs                   DOUBLE       NULL,
    non_meta_facebook_orders            DOUBLE       NULL,
    meta_conversion_value               DOUBLE       NULL,
    meta_facebook_orders                DOUBLE       NULL,
    website_purchases                   DOUBLE       NULL,
    one_day_view_conversion_value       DOUBLE       NULL,
    one_day_view_purchases              DOUBLE       NULL,
    seven_day_view_conversion_value     DOUBLE       NULL,
    seven_day_view_purchases            DOUBLE       NULL,
    channel_reported_conversion_value   DOUBLE       NULL,
    channel_reported_conversions        DOUBLE       NULL,
    channel_reported_onsite_conversion_value DOUBLE  NULL,
    channel_reported_onsite_purchases   DOUBLE       NULL,
    channel_reported_visits             DOUBLE       NULL,
    ad_copies                           TEXT         NULL,
    ad_titles                           TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date, channel, ad_id, asset_id)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

_TW_AI_VISIBILITY = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tw_ai_visibility (
    event_date  DATE         NOT NULL,
    data        TEXT         NULL
) ENGINE=OLAP UNIQUE KEY(event_date)
DISTRIBUTED BY HASH(event_date) BUCKETS 4
PROPERTIES ("replication_num" = "1")"""

# ---------------------------------------------------------------------------
# TikTok ODS 表
# ---------------------------------------------------------------------------

_TIKTOK_RETURN_REFUND = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tiktok_return_refund (
    shop_id VARCHAR(50) COMMENT 'Shop ID (DTC)',
    return_id VARCHAR(255) COMMENT 'Return ID (unique key)',
    shop_name VARCHAR(255) COMMENT 'Shop name (DTC)',
    combined_return_id VARCHAR(255) COMMENT 'Combined return ID',
    order_id VARCHAR(255) COMMENT 'Order ID',
    create_time BIGINT COMMENT 'Create time (unix timestamp)',
    update_time BIGINT COMMENT 'Update time (unix timestamp)',
    return_type VARCHAR(50) COMMENT 'Return type',
    return_status VARCHAR(100) COMMENT 'Return status',
    return_method VARCHAR(100) COMMENT 'Return method',
    return_reason VARCHAR(500) COMMENT 'Return reason',
    return_reason_text TEXT COMMENT 'Return reason text',
    return_shipping_document_type VARCHAR(100) COMMENT 'Return shipping document type',
    return_tracking_number VARCHAR(255) COMMENT 'Return tracking number',
    return_provider_id VARCHAR(255) COMMENT 'Return provider ID',
    return_provider_name VARCHAR(255) COMMENT 'Return provider name',
    return_warehouse_address TEXT COMMENT 'Return warehouse address (JSON)',
    shipment_type VARCHAR(100) COMMENT 'Shipment type',
    handover_method VARCHAR(100) COMMENT 'Handover method',
    is_combined_return BOOLEAN COMMENT 'Is combined return',
    is_quick_refund BOOLEAN COMMENT 'Is quick refund',
    `role` VARCHAR(100) COMMENT 'Role',
    refund_amount_currency VARCHAR(20) COMMENT 'Refund amount currency',
    refund_amount_refund_subtotal DECIMAL(18,4) COMMENT 'Refund subtotal',
    refund_amount_refund_shipping_fee DECIMAL(18,4) COMMENT 'Refund shipping fee',
    refund_amount_refund_tax DECIMAL(18,4) COMMENT 'Refund tax',
    refund_amount_refund_total DECIMAL(18,4) COMMENT 'Refund total',
    shipping_fee_amount TEXT COMMENT 'Shipping fee amount breakdown (JSON)',
    discount_amount TEXT COMMENT 'Discount amount breakdown (JSON)',
    return_line_items TEXT COMMENT 'Return line items (JSON)',
    seller_next_action_response TEXT COMMENT 'Seller next action response (JSON)',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(shop_id, return_id) DISTRIBUTED BY HASH(return_id) BUCKETS 10"""

_TIKTOK_VIDEO_PERFORMANCES = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tiktok_video_performances (
    shop_id VARCHAR(50) COMMENT 'Shop ID (DTC)',
    video_id VARCHAR(255) COMMENT 'Video ID',
    collect_date DATE COMMENT 'Data collection date (end_date - 1)',
    shop_name VARCHAR(255) COMMENT 'Shop name (DTC)',
    title VARCHAR(500) COMMENT 'Video title',
    username VARCHAR(255) COMMENT 'Creator username',
    video_post_time BIGINT COMMENT 'Video post time (unix timestamp)',
    duration INT COMMENT 'Video duration (seconds)',
    views BIGINT COMMENT 'Total views',
    items_sold BIGINT COMMENT 'Items sold',
    sku_orders BIGINT COMMENT 'SKU orders',
    avg_customers DECIMAL(10,4) COMMENT 'Average customers',
    click_through_rate DECIMAL(10,4) COMMENT 'Click through rate',
    gmv_amount DECIMAL(18,4) COMMENT 'GMV amount',
    gmv_currency VARCHAR(20) COMMENT 'GMV currency',
    gpm_amount DECIMAL(18,4) COMMENT 'GPM amount',
    gpm_currency VARCHAR(20) COMMENT 'GPM currency',
    hash_tags TEXT COMMENT 'Hash tags (JSON)',
    products TEXT COMMENT 'Products (JSON)',
    latest_available_date VARCHAR(50) COMMENT 'Latest available date',
    next_page_token VARCHAR(500) COMMENT 'Next page token',
    total_count INT COMMENT 'Total count',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(shop_id, video_id, collect_date) DISTRIBUTED BY HASH(video_id) BUCKETS 10"""

_TIKTOK_SHOP_PRODUCT_PERFORMANCE = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tiktok_shop_product_performance (
    shop_id VARCHAR(50) COMMENT 'Shop ID (DTC)',
    product_id VARCHAR(255) COMMENT 'Product ID',
    collect_date DATE COMMENT 'Data collection date (end_date - 1)',
    shop_name VARCHAR(255) COMMENT 'Shop name (DTC)',
    start_date VARCHAR(20) COMMENT 'Interval start date',
    end_date VARCHAR(20) COMMENT 'Interval end date',
    sales_gmv_amount DECIMAL(18,4) COMMENT 'Sales GMV amount',
    sales_gmv_currency VARCHAR(20) COMMENT 'Sales GMV currency',
    sales_items_sold BIGINT COMMENT 'Sales items sold',
    sales_orders BIGINT COMMENT 'Sales orders',
    sales_avg_customers DECIMAL(10,4) COMMENT 'Sales average customers',
    sales_breakdowns TEXT COMMENT 'Sales breakdowns by content type (JSON)',
    traffic_avg_conversion_rate DECIMAL(10,4) COMMENT 'Traffic average conversion rate',
    traffic_avg_unique_page_views DECIMAL(10,4) COMMENT 'Traffic average unique page views',
    traffic_ctr DECIMAL(10,4) COMMENT 'Traffic CTR',
    traffic_impressions BIGINT COMMENT 'Traffic impressions',
    traffic_page_views BIGINT COMMENT 'Traffic page views',
    traffic_breakdowns TEXT COMMENT 'Traffic breakdowns by content type (JSON)',
    ratings TEXT COMMENT 'Ratings distribution (JSON)',
    top_contents TEXT COMMENT 'Top contents (JSON)',
    top_creators TEXT COMMENT 'Top creators (JSON)',
    latest_available_date VARCHAR(50) COMMENT 'Latest available date',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(shop_id, product_id, collect_date) DISTRIBUTED BY HASH(product_id) BUCKETS 10"""

_TIKTOK_SHOP_VIDEO_PERFORMANCE_DETAIL = """CREATE TABLE IF NOT EXISTS hqware_test.ods_tiktok_shop_video_performance_detail (
    shop_id VARCHAR(50) COMMENT 'Shop ID (DTC)',
    video_id VARCHAR(255) COMMENT 'Video ID',
    collect_date DATE COMMENT 'Data collection date (end_date - 1)',
    shop_name VARCHAR(255) COMMENT 'Shop name (DTC)',
    start_date VARCHAR(20) COMMENT 'Interval start date',
    end_date VARCHAR(20) COMMENT 'Interval end date',
    traffic_views BIGINT COMMENT 'Traffic views',
    traffic_likes BIGINT COMMENT 'Traffic likes',
    traffic_comments BIGINT COMMENT 'Traffic comments',
    traffic_shares BIGINT COMMENT 'Traffic shares',
    traffic_new_followers BIGINT COMMENT 'Traffic new followers',
    sales_overall_customers BIGINT COMMENT 'Sales overall customers',
    sales_overall_items_sold BIGINT COMMENT 'Sales overall items sold',
    sales_overall_gmv_amount DECIMAL(18,4) COMMENT 'Sales overall GMV amount',
    sales_overall_gmv_currency VARCHAR(20) COMMENT 'Sales overall GMV currency',
    sales_overall_gpm_amount DECIMAL(18,4) COMMENT 'Sales overall GPM amount',
    sales_overall_gpm_currency VARCHAR(20) COMMENT 'Sales overall GPM currency',
    sales_overall_ctr DECIMAL(10,4) COMMENT 'Sales overall CTR',
    sales_overall_product_clicks BIGINT COMMENT 'Sales overall product clicks',
    sales_overall_product_impressions BIGINT COMMENT 'Sales overall product impressions',
    sales_breakdowns TEXT COMMENT 'Sales breakdowns by product (JSON)',
    viewer_profile TEXT COMMENT 'Viewer profile (JSON)',
    latest_available_date VARCHAR(50) COMMENT 'Latest available date',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(shop_id, video_id, collect_date) DISTRIBUTED BY HASH(video_id) BUCKETS 10"""

# ---------------------------------------------------------------------------
# 钉钉 ODS 表（中文字段 → 英文 snake_case，COMMENT 写原中文）
# ---------------------------------------------------------------------------

_DINGTALK_KOL_INFO = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_kol_tidwe_kol_info (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    kol_id VARCHAR(255) COMMENT '*红人ID',
    full_name VARCHAR(500) COMMENT '*全名',
    follower_count VARCHAR(100) COMMENT '*粉丝数（k）',
    kol_level VARCHAR(100) COMMENT '红人等级',
    kol_type VARCHAR(100) COMMENT '红人类型',
    cooperation_mode VARCHAR(255) COMMENT '*合作模式',
    payment_mode VARCHAR(255) COMMENT '*付费模式',
    commission_rate VARCHAR(100) COMMENT '*佣金率',
    price_and_delivery TEXT COMMENT '*合作价格及交付项（格式：合作周期-价格-交付内容）',
    sample_address TEXT COMMENT '*寄样地址',
    homepage_url TEXT COMMENT '*主页链接',
    email VARCHAR(500) COMMENT '*Email',
    other_contact VARCHAR(500) COMMENT '其他联系方式',
    payment_info TEXT COMMENT '*收款信息',
    promo_code VARCHAR(255) COMMENT '*Code',
    state VARCHAR(255) COMMENT '*所在州',
    follow_up_person VARCHAR(255) COMMENT '*跟进人',
    cooperation_review TEXT COMMENT '合作review',
    q4_2025_gmv VARCHAR(100) COMMENT '2025Q4 GMV',
    q4_2025_views VARCHAR(100) COMMENT '2025Q4播放',
    long_video_avg_views VARCHAR(100) COMMENT '长视频均播（k）',
    next_action TEXT COMMENT '后续动作',
    notes TEXT COMMENT '备注',
    original_utm VARCHAR(500) COMMENT '原UTM',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_KOL_SAMPLE = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_kol_tidwe_sample (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    kol_id VARCHAR(255) COMMENT '*红人ID',
    product VARCHAR(500) COMMENT '*产品',
    sample_date VARCHAR(100) COMMENT '*寄样时间',
    tracking_number VARCHAR(255) COMMENT '*单号',
    sample_purpose VARCHAR(500) COMMENT '寄样目的',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_KOL_CONTENT = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_kol_tidwe_content (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    kol_id VARCHAR(255) COMMENT '*红人ID',
    publish_platform VARCHAR(255) COMMENT '*发布平台',
    actual_publish_date VARCHAR(100) COMMENT '*实际发布日期',
    expected_publish_date VARCHAR(100) COMMENT '*预期发布日期',
    content_url TEXT COMMENT '*内容发布链接',
    content_type VARCHAR(255) COMMENT '*内容类型',
    cooperation_price TEXT COMMENT '*合作价格（日期：价格/交付内容）',
    promoted_product TEXT COMMENT '*推广产品',
    promo_code VARCHAR(255) COMMENT '*CODE',
    cooperation_mode VARCHAR(255) COMMENT '合作模式',
    cooperation_purpose VARCHAR(500) COMMENT '合作目的',
    contract VARCHAR(255) COMMENT '*合同',
    w9 VARCHAR(255) COMMENT 'W9',
    views VARCHAR(100) COMMENT '播放数',
    notes TEXT COMMENT '备注',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_RAW_MATERIAL = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_outdoor_raw_material (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    date VARCHAR(100) COMMENT '⏱️date',
    script TEXT COMMENT '拍摄脚本（要求全英文）',
    requester VARCHAR(255) COMMENT '需求人',
    material_type VARCHAR(255) COMMENT '素材类型',
    product_sku VARCHAR(500) COMMENT '产品SKU',
    product_spu VARCHAR(500) COMMENT '产品SPU',
    material_quantity VARCHAR(100) COMMENT '素材数量',
    producer VARCHAR(255) COMMENT '制作人/KOL对接人',
    shooting_kol VARCHAR(255) COMMENT '拍摄KOL',
    actual_completion_date VARCHAR(100) COMMENT '实际完成时间',
    material_path TEXT COMMENT '返回素材挂载盘路径',
    cooperation_price VARCHAR(500) COMMENT '合作价格',
    brand VARCHAR(255) COMMENT '品牌',
    material_progress VARCHAR(255) COMMENT '素材进度',
    social_media_person VARCHAR(255) COMMENT '社媒/内容负责人',
    kol_video_url TEXT COMMENT 'KOL上线视频链接',
    multi_channel_use VARCHAR(255) COMMENT '多渠道使用',
    actual_shipping_sku VARCHAR(500) COMMENT '实际发货sku',
    actual_shipping_date VARCHAR(100) COMMENT '实际发货时间',
    need_lock_warehouse VARCHAR(50) COMMENT '是否需要锁仓',
    need_sample VARCHAR(50) COMMENT '是否发样品',
    tiktok_code VARCHAR(255) COMMENT 'Tiktok code',
    expected_return_date VARCHAR(100) COMMENT '预期返回时间',
    tts_script_ref TEXT COMMENT 'TTS爆款脚本参考',
    is_collab_video VARCHAR(50) COMMENT '是否合创视频',
    lock_notes TEXT COMMENT '锁仓备注',
    unlock_notes TEXT COMMENT '解仓备注',
    kol_notes TEXT COMMENT 'KOL备注',
    last_updated_at VARCHAR(100) COMMENT '最后更新时间',
    created_at VARCHAR(100) COMMENT '创建时间',
    updated_by VARCHAR(255) COMMENT '更新人',
    created_by VARCHAR(255) COMMENT '创建人',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_SHOOT_KOL = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_outdoor_shoot_kol (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    shoot_kol VARCHAR(255) COMMENT '拍摄KOL',
    cooperation_phase VARCHAR(255) COMMENT 'Cooperation Phase-合作状态',
    email VARCHAR(500) COMMENT '*Email',
    size VARCHAR(100) COMMENT 'Size',
    gender VARCHAR(50) COMMENT 'Gender',
    contract_date VARCHAR(100) COMMENT 'Contract Date-签合同时间',
    price_note TEXT COMMENT 'Price Note',
    good_at_type TEXT COMMENT '擅长类型',
    good_at_content TEXT COMMENT '擅长内容',
    cooperation_quality VARCHAR(100) COMMENT '配合度',
    content_quality VARCHAR(100) COMMENT '内容质量',
    ad_effect VARCHAR(100) COMMENT '内容投放效果',
    promo_code VARCHAR(255) COMMENT 'Promo Code',
    channel VARCHAR(255) COMMENT 'Channel',
    followers VARCHAR(100) COMMENT 'Followers',
    sample_address TEXT COMMENT '*寄样地址',
    brand VARCHAR(255) COMMENT 'Brand',
    feature_note TEXT COMMENT 'Feature Note-备注',
    real_name VARCHAR(255) COMMENT 'Real Name',
    cooperation_form VARCHAR(255) COMMENT 'Cooperation-合作形式',
    w9_contract VARCHAR(255) COMMENT 'W9和Contract-合同',
    country VARCHAR(255) COMMENT '国家',
    ethnicity VARCHAR(100) COMMENT '民族',
    whatsapp VARCHAR(255) COMMENT 'Whatsapp',
    phone VARCHAR(255) COMMENT 'Phone',
    kol_level VARCHAR(100) COMMENT '红人等级',
    cooperation_mode VARCHAR(255) COMMENT '合作模式',
    payment_mode VARCHAR(255) COMMENT '付费模式',
    tiktok_url TEXT COMMENT 'TK主页链接',
    fb_ig_url TEXT COMMENT 'FB/IG主页链接',
    youtube_url TEXT COMMENT 'YTB主页链接',
    contact_person VARCHAR(255) COMMENT '🤵对接人',
    brand_required VARCHAR(255) COMMENT '品牌',
    is_tiktok_partner VARCHAR(50) COMMENT '是否是TK已合作达人',
    shoot_return_timeliness VARCHAR(100) COMMENT '拍摄返图时效',
    created_at VARCHAR(100) COMMENT '创建时间',
    updated_by VARCHAR(255) COMMENT '更新人',
    last_updated_at VARCHAR(100) COMMENT '最后更新时间',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_VIDEO_DELIVERY = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_video_delivery (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    completion_date VARCHAR(100) COMMENT '成片日期',
    product_spu VARCHAR(500) COMMENT '产品SPU',
    video_title VARCHAR(500) COMMENT '视频标题',
    video_path TEXT COMMENT '视频Y盘路径',
    tt_ad_account VARCHAR(255) COMMENT 'TT投放账号',
    product_category VARCHAR(255) COMMENT '产品大类',
    publish_url TEXT COMMENT '发布链接',
    director VARCHAR(255) COMMENT '编导',
    editor VARCHAR(255) COMMENT '剪辑',
    content_category VARCHAR(255) COMMENT '内容大类',
    dubbing VARCHAR(255) COMMENT '配音',
    brand VARCHAR(255) COMMENT '品牌',
    target_platform VARCHAR(255) COMMENT '针对平台',
    is_published_tt VARCHAR(50) COMMENT '是否发布TT',
    is_sent_to_group VARCHAR(50) COMMENT '是否发群',
    publish_date VARCHAR(100) COMMENT '发布日期',
    special_project VARCHAR(255) COMMENT '特殊项目',
    notes TEXT COMMENT '备注',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_MATERIAL_ANALYSIS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_outdoor_material_analysis (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    jo VARCHAR(255) COMMENT 'Jo',
    date VARCHAR(100) COMMENT 'Date',
    username VARCHAR(255) COMMENT 'Username',
    real_name VARCHAR(255) COMMENT '真名',
    amount_usd VARCHAR(100) COMMENT '金额（USD）',
    include_fee VARCHAR(50) COMMENT '包含手续费',
    round_actual_amount VARCHAR(100) COMMENT 'Round (实际支付金额）',
    cost_sharing VARCHAR(255) COMMENT '费用均摊',
    cost_attribution VARCHAR(255) COMMENT '费用归属',
    store_attribution VARCHAR(255) COMMENT '店铺归属',
    delivery_url TEXT COMMENT '交付链接',
    payment_method VARCHAR(255) COMMENT '支付方式',
    payee_type VARCHAR(100) COMMENT '收款人是个人还是公司',
    contract VARCHAR(255) COMMENT '合同',
    contract_supplement VARCHAR(255) COMMENT '合同补件',
    w9_w8 VARCHAR(255) COMMENT 'W-9/W-8',
    cooperation_content TEXT COMMENT '合作内容',
    other_attachments TEXT COMMENT '其他附件',
    payment_notes TEXT COMMENT '支付备注',
    status VARCHAR(100) COMMENT '状态',
    application_number VARCHAR(255) COMMENT '申请序号',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

_DINGTALK_OUTDOOR_PARAMS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_dingtalk_outdoor_params (
    record_id VARCHAR(255) COMMENT '钉钉行ID (unique key)',
    collected_at DATETIME COMMENT '采集时间',
    raw_data TEXT COMMENT '原始字段数据 (JSON)',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(record_id) DISTRIBUTED BY HASH(record_id) BUCKETS 10"""

# ---------------------------------------------------------------------------
# Awin ODS 表
# ---------------------------------------------------------------------------

_AWIN_TRANSACTIONS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_awin_transactions (
    transaction_id VARCHAR(255) COMMENT 'Transaction ID (unique key)',
    publisher_id VARCHAR(255) COMMENT 'Publisher ID',
    publisher_name VARCHAR(500) COMMENT 'Publisher name',
    commission_status VARCHAR(100) COMMENT 'Commission status',
    commission_amount DECIMAL(18,4) COMMENT 'Commission amount',
    sale_amount DECIMAL(18,4) COMMENT 'Sale amount',
    click_ref VARCHAR(255) COMMENT 'Click reference',
    transaction_date DATETIME COMMENT 'Transaction date',
    validation_date DATETIME COMMENT 'Validation date',
    transaction_type VARCHAR(100) COMMENT 'Transaction type',
    commission_group_id VARCHAR(255) COMMENT 'Commission group ID',
    commission_group_name VARCHAR(500) COMMENT 'Commission group name',
    aov DECIMAL(18,4) COMMENT 'Average order value',
    clicks BIGINT COMMENT 'Clicks',
    impressions BIGINT COMMENT 'Impressions',
    conversion_rate DECIMAL(10,4) COMMENT 'Conversion rate',
    cpa DECIMAL(18,4) COMMENT 'Cost per acquisition',
    cpc DECIMAL(18,4) COMMENT 'Cost per click',
    roi DECIMAL(10,4) COMMENT 'Return on investment',
    total_commission DECIMAL(18,4) COMMENT 'Total commission',
    total_transactions BIGINT COMMENT 'Total transactions',
    total_value DECIMAL(18,4) COMMENT 'Total value',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(transaction_id) DISTRIBUTED BY HASH(transaction_id) BUCKETS 10"""

# ---------------------------------------------------------------------------
# PartnerBoost ODS 表
# ---------------------------------------------------------------------------

_PARTNERBOOST_PERFORMANCE = """CREATE TABLE IF NOT EXISTS hqware_test.ods_partnerboost_performance (
    collect_date DATE COMMENT 'Data collection date',
    publisher_id VARCHAR(255) COMMENT 'Publisher ID',
    partner VARCHAR(500) COMMENT 'Partner name',
    clicks BIGINT COMMENT 'Clicks',
    epc DECIMAL(18,4) COMMENT 'Earnings per click',
    transactions BIGINT COMMENT 'Transactions',
    conversion_rate DECIMAL(10,4) COMMENT 'Conversion rate (%)',
    gross_sales DECIMAL(18,4) COMMENT 'Gross sales',
    aov DECIMAL(18,4) COMMENT 'Average order value',
    avg_commission_rate DECIMAL(10,4) COMMENT 'Average commission rate (%)',
    commission DECIMAL(18,4) COMMENT 'Commission',
    network_fee DECIMAL(18,4) COMMENT 'Network fee',
    total_payout DECIMAL(18,4) COMMENT 'Total payout',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(collect_date, publisher_id) DISTRIBUTED BY HASH(collect_date) BUCKETS 10"""

# ---------------------------------------------------------------------------
# YouTube ODS 表
# ---------------------------------------------------------------------------

_YOUTUBE_VIDEO_STATS = """CREATE TABLE IF NOT EXISTS hqware_test.ods_youtube_video_stats (
    video_id VARCHAR(255) COMMENT 'YouTube video ID (unique key)',
    dingtalk_record_id VARCHAR(255) COMMENT '关联钉钉行ID',
    kind VARCHAR(100) COMMENT 'Resource kind',
    etag VARCHAR(255) COMMENT 'ETag',
    title VARCHAR(500) COMMENT 'Video title (snippet.title)',
    description TEXT COMMENT 'Video description (snippet.description)',
    published_at DATETIME COMMENT 'Published at (snippet.publishedAt)',
    channel_id VARCHAR(255) COMMENT 'Channel ID (snippet.channelId)',
    channel_title VARCHAR(255) COMMENT 'Channel title (snippet.channelTitle)',
    category_id VARCHAR(50) COMMENT 'Category ID (snippet.categoryId)',
    default_language VARCHAR(50) COMMENT 'Default language (snippet.defaultLanguage)',
    default_audio_language VARCHAR(50) COMMENT 'Default audio language',
    live_broadcast_content VARCHAR(50) COMMENT 'Live broadcast content',
    tags TEXT COMMENT 'Tags (JSON, snippet.tags)',
    thumbnail_default_url TEXT COMMENT 'Thumbnail default URL',
    thumbnail_medium_url TEXT COMMENT 'Thumbnail medium URL',
    thumbnail_high_url TEXT COMMENT 'Thumbnail high URL',
    thumbnail_standard_url TEXT COMMENT 'Thumbnail standard URL',
    thumbnail_maxres_url TEXT COMMENT 'Thumbnail maxres URL',
    view_count BIGINT COMMENT 'View count (statistics.viewCount)',
    like_count BIGINT COMMENT 'Like count (statistics.likeCount)',
    comment_count BIGINT COMMENT 'Comment count (statistics.commentCount)',
    favorite_count BIGINT COMMENT 'Favorite count (statistics.favoriteCount)',
    collected_at DATETIME COMMENT '采集时间',
    etl_time DATETIME COMMENT 'ETL写入时间'
) ENGINE=OLAP UNIQUE KEY(video_id) DISTRIBUTED BY HASH(video_id) BUCKETS 10"""

# ---------------------------------------------------------------------------
# 水位线表
# ---------------------------------------------------------------------------

_ETL_WATERMARK = """CREATE TABLE IF NOT EXISTS hqware_test.etl_watermark (
    source VARCHAR(100) COMMENT 'Data source name',
    table_name VARCHAR(255) COMMENT 'Table name',
    last_success_time DATETIME COMMENT 'Last successful sync time',
    run_mode VARCHAR(50) COMMENT 'Run mode (full/incremental)',
    updated_at DATETIME COMMENT 'Watermark updated at'
) ENGINE=OLAP UNIQUE KEY(source, table_name) DISTRIBUTED BY HASH(source) BUCKETS 10"""

# ---------------------------------------------------------------------------
# 建表列表（按数据源分组）
# ---------------------------------------------------------------------------

CREATE_TABLES_SQL = [
    "CREATE DATABASE IF NOT EXISTS hqware_test",
    # TripleWhale — drop old tables first, then recreate with latest schema
    "DROP TABLE IF EXISTS hqware_test.ods_tw_pixel_orders",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_pixel_joined",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_sessions",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_product_analytics",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_pixel_keywords_joined",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_ads",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_social_media_comments",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_social_media_pages",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_creatives",
    "DROP TABLE IF EXISTS hqware_test.ods_tw_ai_visibility",
    _TW_PIXEL_ORDERS,
    _TW_PIXEL_JOINED,
    _TW_SESSIONS,
    _TW_PRODUCT_ANALYTICS,
    _TW_PIXEL_KEYWORDS_JOINED,
    _TW_ADS,
    _TW_SOCIAL_MEDIA_COMMENTS,
    _TW_SOCIAL_MEDIA_PAGES,
    _TW_CREATIVES,
    _TW_AI_VISIBILITY,
    # TikTok
    _TIKTOK_RETURN_REFUND,
    _TIKTOK_VIDEO_PERFORMANCES,
    _TIKTOK_SHOP_PRODUCT_PERFORMANCE,
    _TIKTOK_SHOP_VIDEO_PERFORMANCE_DETAIL,
    # 钉钉
    _DINGTALK_KOL_INFO,
    _DINGTALK_KOL_SAMPLE,
    _DINGTALK_KOL_CONTENT,
    _DINGTALK_RAW_MATERIAL,
    _DINGTALK_SHOOT_KOL,
    _DINGTALK_VIDEO_DELIVERY,
    _DINGTALK_MATERIAL_ANALYSIS,
    _DINGTALK_OUTDOOR_PARAMS,
    # Awin
    _AWIN_TRANSACTIONS,
    # PartnerBoost
    _PARTNERBOOST_PERFORMANCE,
    # YouTube
    _YOUTUBE_VIDEO_STATS,
    # 水位线
    _ETL_WATERMARK,
]


def init_database():
    """Initialize all required ODS tables in Doris."""
    config = DorisConfig()
    db_config = config.DB_CONFIG

    print("=" * 70)
    print("Doris ODS Tables Initialization (CC#4 — full field coverage)")
    print("=" * 70)
    print(f"Host: {db_config['host']}  Port: {db_config['port']}")
    print(f"Tables to create: {len(CREATE_TABLES_SQL) - 1}")
    print("=" * 70)

    try:
        conn = pymysql.connect(**db_config)
        print("\n[OK] Connected to Doris")
        try:
            with conn.cursor() as cursor:
                for i, stmt in enumerate(CREATE_TABLES_SQL, 1):
                    try:
                        cursor.execute(stmt)
                        conn.commit()
                        if 'CREATE TABLE' in stmt:
                            table_name = stmt.split('hqware_test.')[1].split('(')[0].strip()
                            print(f"[{i:2d}] Created: {table_name}")
                        elif 'DROP TABLE' in stmt:
                            table_name = stmt.split('hqware_test.')[1].strip()
                            print(f"[{i:2d}] Dropped: {table_name}")
                        elif 'CREATE DATABASE' in stmt:
                            print(f"[{i:2d}] Database ready")
                    except Exception as e:
                        print(f"[ERROR] Statement {i} failed: {e}")
                        conn.rollback()
                        raise
        finally:
            conn.close()

        print("\n" + "=" * 70)
        print("[SUCCESS] All ODS tables initialized!")
        print("=" * 70)
        return True

    except Exception as e:
        print(f"\n[FAILED] Initialization error: {e}")
        return False


if __name__ == "__main__":
    success = init_database()
    sys.exit(0 if success else 1)
